// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Alert(Props) {
  var text = Props.text;
  return React.createElement("div", undefined, text);
}

var make = Alert;

export {
  Alert
  // uncommenting the next line breaks the props parsing by docz
  // make
};

// Uncommenting the next line does not break props parsing by docz
// export { make };

/* react Not a pure module */
