// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function Alert(Props) {
  var text = Props.text;
  return React.createElement("div", undefined, text);
}

function alert(Props) {
  var text = Props.text;
  return React.createElement("div", undefined, text);
}

function Make(Props) {
  var text = Props.text;
  return React.createElement("div", undefined, "Make: " + text);
}

export { Alert, alert, Make };
/* react Not a pure module */
